$(document).ready(function(){
    $('.cal').click(function(){
        location.assign("calendar.html");
        console.log("calendar");
    });
    $('.home').click(function(){
        location.assign("dashboard.html");
        console.log("dashboard");
    });
    $('.add').click(function(){
        location.assign("add.html");
        console.log("add");
    });
});